export const ROUTES = {
  HOME: "/",
  MOVIES: "movies",
  RECOMENDEDMOVIES: "movies/recomendedMovies",
  NEWMOVIES: "movies/newMovies",
  POPULARMOVIES: "movies/PopularMovies",
  ABOUTUS: "aboutUs",
  ERROR: "*",
  EACHPRODUCT: "movies/:page/:id",
  PROFILE: "profile",
  REGISTRATION: "registration",
  LOGIN: "login",
  PLANS: "plans",
  WATCHLIST: "watchlist",
  SEARCHING: "searching",
  SEARCHED_RESULT_EACH: "searching/:id",
  TERMSOFUSE: "termsOfUse",
  PRIVACYPAGE: "privacyPolicy",
};
